name: Cypress Tests

on:
  deployment_status

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          env: baseUrl=${{ github.event.deployment.payload.web_url }}
        #   build: npm run build
        #   start: npm start
